Add units & Improve CI

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -20,6 +20,19 @@ jobs:
           node-version: 23
           cache: 'npm'
 
+      - name: Check package.json version
+        run: |
+          BASE_VERSION=$(git show origin/main:package.json | jq -r '.version')
+          PR_VERSION=$(jq -r '.version' package.json)
+
+          echo "Base version: $BASE_VERSION"
+          echo "PR version: $PR_VERSION"
+
+          if [ "$BASE_VERSION" = "$PR_VERSION" ]; then
+            echo "Error: Version in package.json must be updated in this PR!"
+            exit 1
+          fi
+
       - name: Install dependencies
         run: npm i --dev
 
